# Generated by Django 3.1.9 on 2021-06-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0003_review_team_whychooseus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
