# Generated by Django 3.1.9 on 2021-06-25 11:12

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ninjawebtech_app', '0004_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=30)),
                ('image1', models.ImageField(upload_to='portfolio')),
                ('image2', models.ImageField(upload_to='portfolio')),
                ('image3', models.ImageField(upload_to='portfolio')),
                ('image4', models.ImageField(upload_to='portfolio')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='ninjawebtech_app.projectcategory')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
