# Generated by Django 3.1.9 on 2021-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0007_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='job',
            field=models.CharField(default='python developer', max_length=60),
        ),
    ]
