# Generated by Django 3.1.9 on 2021-06-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0009_contactdata_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactData',
        ),
    ]
