# Generated by Django 3.1.9 on 2021-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0010_delete_contactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
