# Generated by Django 3.1.9 on 2021-07-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0014_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='thumbnail',
        ),
    ]
