# Generated by Django 3.1.9 on 2021-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0017_review_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image5',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image6',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image7',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
    ]
