# Generated by Django 3.1.9 on 2021-07-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0019_auto_20210703_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdata',
            options={'verbose_name': 'Contact Data', 'verbose_name_plural': 'Contact Data'},
        ),
    ]
