# Generated by Django 3.1.9 on 2021-07-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0020_auto_20210703_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
