# Generated by Django 3.1.9 on 2021-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0023_newsletteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='conf_number',
            field=models.IntegerField(default=0),
        ),
    ]
