# Generated by Django 3.1.9 on 2021-07-05 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0024_newsletteruser_conf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletteruser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
