# Generated by Django 3.1.9 on 2021-07-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0025_auto_20210705_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='conf_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
