# Generated by Django 3.1.9 on 2021-07-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0026_auto_20210705_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterUser',
        ),
    ]
