# Generated by Django 3.1.9 on 2021-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0028_newsletteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='conf_number',
            field=models.CharField(max_length=15),
        ),
    ]
