# Generated by Django 3.1.9 on 2021-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0030_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=30)),
            ],
        ),
    ]
