# Generated by Django 3.1.9 on 2021-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0031_pricingfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='features',
            field=models.ManyToManyField(blank=True, max_length=30, to='ninjawebtech_app.PricingFeatures'),
        ),
    ]
