# Generated by Django 3.1.9 on 2021-08-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0034_auto_20210722_0102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactData',
        ),
    ]
