# Generated by Django 3.1.9 on 2021-08-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0040_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postcategory', to='ninjawebtech_app.postcategory'),
            preserve_default=False,
        ),
    ]
