# Generated by Django 3.1.9 on 2021-10-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0043_postviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_count',
        ),
    ]
