# Generated by Django 3.1.9 on 2021-10-04 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0044_remove_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 14, 14, 7, 150435)),
        ),
    ]
