# Generated by Django 3.1.9 on 2021-10-04 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0045_postviews_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 15, 48, 7, 307382)),
        ),
    ]
