# Generated by Django 3.1.9 on 2021-10-04 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0046_auto_20211004_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 15, 49, 12, 391987)),
        ),
    ]
