# Generated by Django 3.1.9 on 2021-10-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0048_auto_20211005_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
