# Generated by Django 3.1.9 on 2021-10-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0050_blogtags_portfoliotags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotags',
            name='project',
        ),
        migrations.DeleteModel(
            name='BlogTags',
        ),
        migrations.DeleteModel(
            name='PortfolioTags',
        ),
    ]
