# Generated by Django 3.1.9 on 2021-10-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0051_auto_20211006_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project', models.ManyToManyField(blank=True, null=True, to='ninjawebtech_app.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.ManyToManyField(blank=True, null=True, to='ninjawebtech_app.Post')),
            ],
        ),
    ]
