# Generated by Django 3.1.9 on 2021-10-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0052_blogtags_portfoliotags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtags',
            name='post',
            field=models.ManyToManyField(blank=True, to='ninjawebtech_app.Post'),
        ),
        migrations.AlterField(
            model_name='portfoliotags',
            name='project',
            field=models.ManyToManyField(blank=True, to='ninjawebtech_app.Portfolio'),
        ),
    ]
