# Generated by Django 3.2.13 on 2022-06-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0058_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
