# Generated by Django 3.2.13 on 2022-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0061_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbnail',
            field=models.ImageField(default='1', upload_to='comments'),
            preserve_default=False,
        ),
    ]
