# Generated by Django 3.2.13 on 2022-06-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjawebtech_app', '0063_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_en',
        ),
    ]
